[package]
name = "pitr_info"
version = "0.1.0"
authors = ["urlordjames <32751441+urlordjames@users.noreply.github.com>"]
license = "MIT"
edition = "2018"

[dependencies]
pitr_util = { git = "https://github.com/urlordjames/pitr_util", branch = "main" }

[profile.release]
lto = "fat"
